#
# ICGC Docs - Config
#

site_name: ICGC DCC Docs
site_url: http://docs.icgc.org
repo_url: https://github.com/icgc-dcc/dcc-docs
copyright: "&copy; 2015-2016"
google_analytics: ['UA-43425408-2', 'docs.icgc.org']
theme_dir: theme
pages:
- Home: index.md
- Portal:
  - About: 'portal/about.md'
  - Access: 'portal/access.md'
  - Analysis: 'portal/analysis.md'
  - API:
    -  Guide: 'portal/api.md'
    -  Endpoints: 'portal/api-endpoints.md'
  - Methods: 'portal/methods.md'
  - Projects: 'portal/projects.md'
  - Publication: 'portal/publication.md'
  - Releases: 'portal/releases.md'
  - Search: 'portal/search.md'
  - Browsers: 'portal/browsers.md'
- Download:
  - Data Access: 'download/data-access.md'
  - Guide: 'download/guide.md'
  - icgc-get: 'download/icgc-get.md'
  - Repositories: 'download/repositories.md'
- Submission:
  - About: 'submission/about.md'
  - API: 'submission/api.md'
  - Projects: 'submission/projects.md'
  - Institutions: 'submission/institutions.md'
  - FAQ: 'submission/faq.md'
  - Guide:
    - Introduction: 'submission/guide/intro.md'
    - Submitting Raw Data to EGA: 'submission/guide/overview/submitting-raw-data-ega.md'
    - Submission File Format: 'submission/guide/overview/submission-file-format.md'
    - File Submission: 'submission/guide/overview/file-submission.md'
    - Submission Validation: 'submission/guide/overview/submission-validation.md'
    - EGA Raw File Validation: 'submission/guide/ega_file_validation.md'
    - MVEL Script Restriction Example Cases: 'submission/guide/mvel-script-restriction-example-cases.md'
    - Incremental Submission Feature: 'submission/guide/incremental-submission-feature.md'
    - Selective Validation Feature: 'submission/guide/selective-validation-feature.md'
    - DCC Data Element Specifications: 'submission/guide/dcc-data-element-specifications.md'
    - Clinical Data Submission File Specifications: 'submission/guide/clinical-data-submission-file-specifications.md'
    - Donor Clinical Data Guidelines: 'submission/guide/donor-clinical-data-guidelines.md'
    - Sample Type Specification: 'submission/guide/sample-type-specification.md'
    - Experimental Data Submission File Specifications: 'submission/guide/experimental-data-submission-file-specifications.md'
    - Simple Somatic Mutation Format: 'submission/guide/icgc-simple-somatic-mutation-format.md'
  - PCAWG:
    - PanCancer Clinical Data Requirements: 'submission/pcawg/pancancer-clinical-data-requirements.md'
    - FAQ: 'submission/pcawg/pcawg-faq.md'
- Dictionary:
  - About: 'dictionary/about.md'
  - Viewer: 'dictionary/viewer.md'
  - Release Notes:
    - Releases: 'dictionary/releases.md'
    - Release 24: 'dictionary/release-24.md'
    - Release 23: 'dictionary/release-23.md'
    - Release 22: 'dictionary/release-22.md'
    - Release 21: 'dictionary/release-21.md'
    - Release 20: 'dictionary/release-20.md'
    - Release 19: 'dictionary/release-19.md'
    - Release 18: 'dictionary/release-18.md'
    - Release 17: 'dictionary/release-17.md'
    - Release 16: 'dictionary/release-16.md'
    - Release 15: 'dictionary/release-15.md'
- Software:
  - Source Code: 'software/code.md'
  - Download: 'software/download.md'
- PCAWG:
  - About: 'pcawg/index.md'
  - Data Download: 'pcawg/data.md'
extra:
  project_root_dir: '/'
  project_org: 'ICGC'
  project_description: 'DCC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_viewer_base_url: 'https://submissions.dcc.icgc.org'
  dictionary_viewer_js_rel_url: '/dictionary/scripts/dictionary.js'
  dictionary_viewer_css_rel_url: '/dictionary/styles/dictionary.css'
  api_endpoint_page_id: 'API Endpoints'
  resources:
    Browsers:
      styles:
        - //maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
    Binaries:
      scripts:
        - /js-out/software-page.js
      styles:
        - /css-out/software-page.css
    Viewer:
      scripts:
        - /js-out/dictionary-viewer.js
      styles:
        - /vendor/angular-loading-bar/loading-bar.min.css
        - https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.1.5/jsoneditor.css
        - /css-out/dictionary-viewer.css
    Home:
      styles:
        - https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,500italic,700,700italic|Roboto+Mono:400,500,700|Material+Icons
        - /css-out/homepage.css
