site_name: ICGC Docs
site_url: http://icgc.github.io
repo_url: https://github.com/icgc/icgc-docs
copyright: "&copy; 2015 ICGC.org"
theme_dir: theme
pages:
- Home: index.md
- Portal:
  - About: 'portal/about.md'
  - Search: 'portal/search.md'
- Cloud:
  - Guide: 'cloud/guide.md'
- Submission:
  - About: 'submission/about.md'

