#
# ICGC Docs - Config
#

site_name: ICGC Docs
site_url: http://icgc.github.io
repo_url: https://github.com/icgc/icgc-docs
copyright: "&copy; 2015 ICGC.org"
theme_dir: theme
pages:
- Home: index.md
- Portal:
  - About: 'portal/about.md'
  - Access: 'portal/access.md'
  - Analysis: 'portal/analysis.md'
  - API: 'portal/api.md'
  - Methods: 'portal/methods.md'
  - Projects: 'portal/projects.md'
  - Publication: 'portal/publication.md'
  - Releases: 'portal/releases.md'
  - Repositories: 'portal/repositories.md'
  - Search: 'portal/search.md'
  - Software: 'portal/software.md'
- Cloud:
  - About: 'cloud/about.md'
  - Guide: 'cloud/guide.md'
- Submission:
  - About: 'submission/about.md'
  - API: 'submission/api.md'
  - Dictionary: 'submission/dictionary.md'
  - Dictionary - Release 20: 'submission/dictionary_20.md'
  - Dictionary - Release 19: 'submission/dictionary_19.md'
  - Dictionary - Release 18: 'submission/dictionary_18.md'
  - Dictionary - Release 17: 'submission/dictionary_17.md'
  - Dictionary - Release 16: 'submission/dictionary_16.md'
  - Dictionary - Release 15: 'submission/dictionary_15.md'
  - Guide: 'submission/guide.md'
  - Software: 'submission/software.md'

