#
# ICGC Docs - Config
#

site_name: ICGC Docs
site_url: http://icgc.github.io
repo_url: https://github.com/icgc/icgc-docs
copyright: "&copy; 2015 ICGC.org"
theme_dir: theme
pages:
- Home: index.md
- Portal:
  - About: 'portal/about.md'
  - Access: 'portal/access.md'
  - Analysis: 'portal/analysis.md'
  - API: 'portal/api.md'
  - Methods: 'portal/methods.md'
  - Projects: 'portal/projects.md'
  - Publication: 'portal/publication.md'
  - Releases: 'portal/releases.md'
  - Repositories: 'portal/repositories.md'
  - Search: 'portal/search.md'
  - Software: 'portal/software.md'
- Cloud:
  - About: 'cloud/about.md'
  - Guide: 'cloud/guide.md'
- Submission:
  - About: 'submission/about.md'
  - API: 'submission/api.md'
  - Dictionary: 'submission/dictionary.md'
  - Dictionary - Release 20:
    - Dictionary - Release 20: 'submission/dictionary/20.md'
    - Analyzed Sample Data File (sample): 'submission/dictionary/20/analyzed-sample-data-file-sample.md'
    - Array-based DNA Methylation (meth_array) - Analysis Metadata File (m): 'submission/dictionary/20/array-based-dna-methylation-metharray-analysis-metadata-file-m.md'
    - Array-based DNA Methylation (meth_array) - Primary File (p): 'submission/dictionary/20/array-based-dna-methylation-metharray-primary-file-p.md'
    - Array-based Gene Expression (exp_array) - Analysis Metadata File (m): 'submission/dictionary/20/array-based-gene-expression-exparray-analysis-metadata-file-m.md'
    - Array-based Gene Expression (exp_array) - Primary File (p): 'submission/dictionary/20/array-based-gene-expression-exparray-primary-file-p.md'
    - Controlled Vocabulary (CV) Tables: 'submission/dictionary/20/controlled-vocabulary.md'
    - Copy Number Somatic Mutations (cnsm) - Analysis Metadata File (m): 'submission/dictionary/20/copy-number-somatic-mutations-cnsm-analysis-metadata-file-m.md'
    - Copy Number Somatic Mutations (cnsm) - Primary Analysis File (p): 'submission/dictionary/20/copy-number-somatic-mutations-cnsm-primary-analysis-file-p.md'
    - Copy Number Somatic Mutations (cnsm) - Secondary Analysis File (s): 'submission/dictionary/20/copy-number-somatic-mutations-cnsm-secondary-analysis-file-s.md'
    - Donor Biomarkers (biomarker): 'submission/dictionary/20/donor-biomarker.md'
    - Donor Data File (donor): 'submission/dictionary/20/donor-data-file-donor.md'
    - Donor Exposure (exposure): 'submission/dictionary/20/donor-exposure.md'
    - Donor Family (family): 'submission/dictionary/20/donor-family.md'
    - Donor Postresection Therapy (therapy): 'submission/dictionary/20/donor-postresection-therapy.md'
    - Donor Surgery (surgery): 'submission/dictionary/20/donor-surgery.md'
    - Protein Expression (pexp) - Analysis Metadata File (m): 'submission/dictionary/20/protein-expression-pexp-analysis-metadata-file-m.md'
    - Protein Expression (pexp) - Primary Analysis File (p): 'submission/dictionary/20/protein-expression-pexp-primary-analysis-file-p.md'
    - Sequencing-based DNA Methylation (meth_seq) - Analysis Metadata File (m): 'submission/dictionary/20/sequencing-based-dna-methylation-methseq-analysis-metadata-file-m.md'
    - Protein Expression (pexp) - Primary Analysis File (p): 'submission/dictionary/20/sequencing-based-dna-methylation-methseq-primary-file-p.md'
    - Sequencing-based Gene Expression (exp_seq) - Analysis Metadata File (m): 'submission/dictionary/20/sequencing-based-gene-expression-expseq-analysis-metadata-file-m.md'
    - Sequencing-based Gene Expression (exp_seq) - Primary File (p): 'submission/dictionary/20/sequencing-based-gene-expression-expseq-primary-file-p.md'
    - Sequencing-based miRNA Expression (mirna_seq) - Analysis Metadata File (m): 'submission/dictionary/20/sequencing-based-mirna-expression-mirnaseq-analysis-metadata-file-m.md'
    - Sequencing-based miRNA Expression (mirna_seq) - Primary File (p): 'submission/dictionary/20/sequencing-based-mirna-expression-mirnaseq-primary-file-p.md'
    - Simple Germline Variation (sgv) - Analysis Metadata File (m): 'submission/dictionary/20/simple-germline-variation-sgv-analysis-metadata-file-m.md'
    - Simple Germline Variation (sgv) - Primary Analysis File (p): 'submission/dictionary/20/simple-germline-variation-sgv-primary-analysis-file-p.md'
    - Simple Somatic Mutations (ssm) - Analysis Metadata File (m): 'submission/dictionary/20/simple-somatic-mutations-ssm-analysis-metadata-file-m.md'
    - Simple Somatic Mutations (ssm) - Primary Analysis File (p): 'submission/dictionary/20/simple-somatic-mutations-ssm-primary-analysis-file-p.md'
    - Specimen Data File (specimen): 'submission/dictionary/20/specimen-data-file-specimen.md'
    - Splice Variation (jcn) - Analysis Metadata File (m): 'submission/dictionary/20/splice-variation-jcn-analysis-metadata-file-m.md'
    - Splice Variation (jcn) - Primary Analysis File (p): 'submission/dictionary/20/splice-variation-jcn-primary-analysis-file-p.md'
    - Structural Somatic Mutations (stsm) - Analysis Metadata File (m): 'submission/dictionary/20/structural-somatic-mutations-stsm-analysis-metadata-file-m.md'
    - Structural Somatic Mutations (stsm) - Primary Analysis File (p): 'submission/dictionary/20/structural-somatic-mutations-stsm-primary-analysis-file-p.md'
    - Structural Somatic Mutations (stsm) - Secondary Analysis File (s): 'submission/dictionary/20/structural-somatic-mutations-stsm-secondary-analysis-file-s.md'
  - Dictionary - Release 19: 'submission/dictionary/dictionary-19.md'
  - Dictionary - Release 18: 'submission/dictionary/dictionary-18.md'
  - Dictionary - Release 17: 'submission/dictionary/dictionary-17.md'
  - Dictionary - Release 16: 'submission/dictionary/dictionary-16.md'
  - Dictionary - Release 15: 'submission/dictionary/dictionary-15.md'
  - FAQ: 'submission/faq.md'
  - Guide: 'submission/guide.md'
  - Software: 'submission/software.md'